### Numpy
Date: October 6, 2019

* Python package for scientific computing
* Comes in 2 flavors, vectors and matrices

In [1]:
import numpy as np

#### Numpy array creation

1. creation from other python structures
2. intrinsic numpy array (arange, ones, zeros)
3. reading array from disk
4. creating array from raw bytes
5. use of special library (e.g random)

In [12]:
# creation from other python structures
# python list
numbers = [1,2,3] 

np.array(numbers)

array([1, 2, 3])

In [13]:
#creating 2 dimentional numpy array
numbers = [[1,2,3],[4,5,6],[7,8,9]]

np.array(numbers)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# creating numpy array from intrinsic numpy function
# 1. numpy.arange - arange([start,] stop[, step,], dtype=None)

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [20]:
# 2. creating an array of zeros
# np.zeros() - zeros(shape, dtype=float, order='C')

np.zeros(10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
# 2 dimentional
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# np.ones - np.ones(shape, dtype=None, order='C')

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
# 2 dimentional 
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
# linspace - np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
np.linspace(0, 5, 100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [27]:
# identity matrix
# eye - np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
# this will return 2 dimentional array

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [29]:
# identity matrix
# np.identity - np.identity(n, dtype=None)

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
# creating numpy array from special library

np.random.rand(4,5)

array([[0.42274969, 0.06671955, 0.84109597, 0.47418012, 0.9962958 ],
       [0.53918168, 0.14523875, 0.9508027 , 0.01412936, 0.44944524],
       [0.39554715, 0.73100484, 0.60010782, 0.6338287 , 0.93777568],
       [0.59221079, 0.12038885, 0.72605709, 0.22825759, 0.11344048]])

In [33]:
# creating random numpy array with gaussian distribution or the standard normal distribution

np.random.randn(4,5)

array([[-0.7273268 , -1.08827905,  0.68172995, -1.83349413,  0.74650021],
       [ 0.18278022, -1.57079197,  0.07823191, -0.75231749,  0.49212022],
       [ 0.00920349,  1.06223084, -0.98618981, -0.35196447,  0.98146273],
       [ 0.12887381,  1.18955451, -0.11781384,  0.36907741, -0.19928681]])

In [35]:
# creating numpy array with randon integers
#randint(low, high=None, size=None, dtype='l')

np.random.randint(1, 50, 10)

array([44,  6, 20,  3, 49, 40, 13, 46, 11,  5])

### Common numpy array methods
* shape
* reshape
* min
* max
* argmax
* argmin
* dtype

In [39]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
arr.shape

(25,)

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
arr = np.random.randint(1, 100, 50)
arr

array([52, 96, 51, 60, 59, 62, 55, 58, 81, 84, 58, 84, 33, 70, 24, 95, 20,
       31, 15, 59, 41, 48, 74, 70, 77, 74, 44, 70,  9, 92, 16,  1, 46, 88,
       73, 35,  7, 18, 31, 49, 88, 59, 86, 81, 32, 58, 52, 12,  5, 96])

In [60]:
# get the maximum value in the numpy array
arr.max()

96

In [61]:
# retrieve the index of the max value of the numpy array
arr.argmax()

1

In [62]:
# get the minimum value in the numpy array
arr.min()

1

In [63]:
# retrieve the index of the min value of the numpy array
arr.argmin()

31

In [67]:
arr.dtype

dtype('int32')

### Numpy Array Indexing
* numpyArray[indexNumber]
* numpyArray[start:stop:step]

In [68]:
arr = np.arange(0,11)

In [69]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
# retrieve a single value of the specified index
arr[9]

9

In [72]:
# array slicing 1
#note indexing will start at 0
arr[1:6]

array([1, 2, 3, 4, 5])

In [73]:
# array slicing 2
arr[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [75]:
# array slicing 3
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Indexing Multidimentional numpy array
* double bracket format
* single bracket format/slice notation

In [80]:
# create a 2 dimentional randint array
arr = np.random.randint(1, 50, size=(5,5))
arr

array([[ 2,  4, 45, 35, 28],
       [27, 26,  4, 37,  3],
       [ 1, 37, 16, 26, 15],
       [42, 43, 26, 40,  4],
       [29, 11, 15, 32, 17]])

In [81]:
# double bracket format
# get the value from row 1, col 1
arr[1][1]

26

In [83]:
# slice notation - useful when you want to grab a sub set of the array
# grab the section
# [2, 4, 45]
# [27, 26, 4]

arr[:2,:3]

array([[ 2,  4, 45],
       [27, 26,  4]])

In [84]:
# grab the last 2 rows of the array
arr[3:,:]

array([[42, 43, 26, 40,  4],
       [29, 11, 15, 32, 17]])

### Conditional selection

In [87]:
# create a random integer array
arr = np.random.randint(1, 100, size=(5,5))
arr

array([[41, 80, 76, 75, 81],
       [63, 46, 22, 17, 45],
       [29, 66, 95, 46, 52],
       [32, 30, 44, 51, 47],
       [55, 88, 60, 17, 12]])

In [88]:
# use conditional operator to the array
# this will return a Boolean value 
# True if it satisfy the condition otherwise False
arr > 50

array([[False,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False,  True,  True, False,  True],
       [False, False, False,  True, False],
       [ True,  True,  True, False, False]])

In [89]:
bool_arr = arr > 50

In [91]:
arr_greater_than_50 = arr[bool_arr]
arr_greater_than_50

array([80, 76, 75, 81, 63, 66, 95, 52, 51, 55, 88, 60])